% COMSOL Multiphysics Model M-file
% Generated by COMSOL 3.5a (COMSOL 3.5.0.603, $Date: 2008/12/03 17:02:19 $)

flclear fem

% COMSOL version
clear vrsn
vrsn.name = 'COMSOL 3.5';
vrsn.ext = 'a';
vrsn.major = 0;
vrsn.build = 603;
vrsn.rcs = '$Name:  $';
vrsn.date = '$Date: 2008/12/03 17:02:19 $';
fem.version = vrsn;

% Constants
fem.const = {'hbar','1.054571628e-34', ...
  'q','1.602176487e-19', ...
  'm0','9.10938215e-31', ...
  'R','20', ...
  'B','0', ...
  'l','0', ...
  'sfa','hbar^2/2/m0/R^2/1e-18/q*1e3', ...
  'sfb','hbar*q*B/m0/q*1e3', ...
  'sfc','q^2*B^2*R^2*1e-18/m0/q*1e3', ...
  'mdot','0.0465', ...
  'mbar','0.067', ...
  'vdot','0', ...
  'vbar','245'};

% Geometry
g1=solid1([0,1]);
g2=solid1([1,10]);

% Analyzed geometry
clear s
s.objs={g1,g2};
s.name={'I1','I2'};
s.tags={'g1','g2'};

fem.draw=struct('s',s);
fem.geom=geomcsg(fem);


% Initialize mesh
fem.mesh=meshinit(fem, ...
                  'hmaxsub',[1,0.001,2,0.01]);

% (Default values are not included)

% Application mode 1
clear appl
appl.mode.class = 'FlPDEC';
appl.sshape = 2;
appl.assignsuffix = '_c';
clear bnd
bnd.type = {'dir','neu','dir'};
bnd.h = {1,1,0};
bnd.ind = [3,2,1];
appl.bnd = bnd;
clear equ
equ.f = 0;
equ.c = {'sfa/mdot','sfa/mbar'};
equ.a = {'sfa/mdot*l^2/x^2+sfb/mdot*l+sfc/mdot*x^2+vdot','sfa/mbar*l^2/x^2+sfb/mbar*l+sfc/mbar*x^2+vbar'};
equ.be = {'-sfa/mdot/x','-sfa/mbar/x'};
equ.ind = [1,2];
appl.equ = equ;
fem.appl{1} = appl;
fem.frame = {'ref'};
fem.border = 1;

% ODE Settings
clear ode
clear units;
units.basesystem = 'SI';
ode.units = units;
fem.ode=ode;

% Multiphysics
fem=multiphysics(fem);

% Extend mesh
fem.xmesh=meshextend(fem);

% Solve problem
fem.sol=femeig(fem, ...
               'solcomp',{'u'}, ...
               'outcomp',{'u'}, ...
               'blocksize','auto', ...
               'neigs',50);

% Save current fem structure for restart purposes
fem0=fem;

E1=fem.sol.lambda(1);
E2=fem.sol.lambda(2);
fprintf('E1=%f\n',E1);
fprintf('E2=%f\n',E2);

% Plot solution
figure;
postplot(fem, ...
         'liny',{'u','cont','internal'}, ...
         'lincolor',[0.0,0.0,0.0], ...
         'solnum',1, ...
         'axis',[-0.5,10.5]);

% Plot solution
figure;
postplot(fem, ...
         'liny',{'u','cont','internal'}, ...
         'lincolor',[0.0,0.0,0.0], ...
         'solnum',2, ...
         'axis',[-0.5,10.5]);



